// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

error LP_IS_PAUSED();
error ZERO_AMOUNT();
error ZERO_ADDRESS();
error LP_LIQUIDATION_CALL_FAILED();
error CT_CALLER_MUST_BE_LENDING_POOL();
error CT_INVALID_BURN_AMOUNT();
error CT_INVALID_MINT_AMOUNT();
error CT_BURN_EXCEEDS_BALANCE();
error CT_TRANSFER_EXCEEDS_BALANCE();

error MATH_MULTIPLICATION_OVERFLOW();
error MATH_DIVISION_BY_ZERO();
error MATH_ADDITION_OVERFLOW();
